name: JellyfinAPI
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Stepan <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  dio: ^1.0.6
  json_serializable: ^2.2.2
  intl: ^0.15.8
  open_api: ^2.0.1
  strings: ^0.1.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: any
